/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./RealIsland.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={[1, 1, 1]}>
      <group name="AuxScene" >
        <group>
          <group name="Tree">
            <mesh
              material={materials.green1}
              geometry={nodes.pPlane1.geometry}
              name="pPlane1"
              position={[3.8122, 12.0687, -1.1943]}
              rotation={[0.5581, 0, -0.7974]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials.Trunk}
              geometry={nodes.pCylinder1.geometry}
              name="pCylinder1"
              position={[0, 0.286, -2.7959]}
            />
            <mesh
              material={materials.green1}
              geometry={nodes.pPlane2.geometry}
              name="pPlane2"
              position={[4.3027, 12.0687, -1.1943]}
              rotation={[-2.5835, -0.9218, 2.556]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials.green1}
              geometry={nodes.pPlane3.geometry}
              name="pPlane3"
              position={[4.747, 12.1131, -1.1943]}
              rotation={[-2.4235, 0.5357, 2.25]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials.green}
              geometry={nodes.pPlane4.geometry}
              name="pPlane4"
              position={[4.3027, 12.0687, -1.1943]}
              rotation={[-3.0221, 1.4415, 3.0089]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials.green}
              geometry={nodes.pPlane5.geometry}
              name="pPlane5"
              position={[4.6292, 12.2751, -0.9302]}
              rotation={[0.2924, 0.6633, -0.2949]}
              scale={[5.6514, 1.0917, 1.0917]}
            />
            <mesh
              material={materials.green1}
              geometry={nodes.pPlane6.geometry}
              name="pPlane6"
              position={[4.6292, 11.5639, -0.2929]}
              rotation={[0.7545, -1.2296, 0.09]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials.green2}
              geometry={nodes.pPlane7.geometry}
              name="pPlane7"
              position={[3.5114, 12.1685, -0.9515]}
              rotation={[-2.6762, -0.12, 2.8285]}
              scale={[5.8361, 1.1274, 1.1274]}
            />
            <mesh
              material={materials.green2}
              geometry={nodes.pPlane8.geometry}
              name="pPlane8"
              position={[4.4097, 12.3994, -1.218]}
              rotation={[0.6168, -0.7127, -0.5548]}
              scale={[5.6514, 1.0917, 1.0917]}
            />
          </group>
          <group name="tree_2Tree" rotation={[-Math.PI, -0.6443, -Math.PI]}>
            <mesh
              material={materials['tree_2:green1']}
              geometry={nodes.tree_2pPlane1.geometry}
              name="tree_2pPlane1"
              position={[4.0456, 6.0633, -11.1365]}
              rotation={[-0.3259, 0, -0.7974]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials['tree_2:Trunk']}
              geometry={nodes.tree_2pCylinder1.geometry}
              name="tree_2pCylinder1"
              position={[0, 0.286, -2.7959]}
            />
            <mesh
              material={materials['tree_2:green1']}
              geometry={nodes.tree_2pPlane2.geometry}
              name="tree_2pPlane2"
              position={[4.1222, 6.6353, -10.3082]}
              rotation={[2.7272, -0.9609, 2.989]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials['tree_2:green1']}
              geometry={nodes.tree_2pPlane3.geometry}
              name="tree_2pPlane3"
              position={[4.9803, 6.1077, -11.1365]}
              rotation={[2.9756, 0.5357, 2.25]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials['tree_2:green']}
              geometry={nodes.tree_2pPlane4.geometry}
              name="tree_2pPlane4"
              position={[4.536, 6.0633, -11.1365]}
              rotation={[2.3771, 1.4415, 3.0089]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials['tree_2:green']}
              geometry={nodes.tree_2pPlane5.geometry}
              name="tree_2pPlane5"
              position={[4.8626, 6.2696, -10.8724]}
              rotation={[-0.5916, 0.6633, -0.2949]}
              scale={[5.6514, 1.0917, 1.0917]}
            />
            <mesh
              material={materials['tree_2:green1']}
              geometry={nodes.tree_2pPlane6.geometry}
              name="tree_2pPlane6"
              position={[4.8626, 6.3538, -10.2351]}
              rotation={[-0.1295, -1.2296, 0.09]}
              scale={[6.6741, 1.2893, 1.2893]}
            />
            <mesh
              material={materials['tree_2:green2']}
              geometry={nodes.tree_2pPlane7.geometry}
              name="tree_2pPlane7"
              position={[3.7448, 6.5398, -10.8937]}
              rotation={[2.6239, -0.3876, 2.842]}
              scale={[5.8361, 1.1274, 1.1274]}
            />
            <mesh
              material={materials['tree_2:green2']}
              geometry={nodes.tree_2pPlane8.geometry}
              name="tree_2pPlane8"
              position={[4.6431, 6.394, -11.1602]}
              rotation={[-0.2672, -0.7127, -0.5548]}
              scale={[5.6514, 1.0917, 1.0917]}
            />
          </group>
          <mesh
            material={materials.phong1}
            geometry={nodes.pSphere1.geometry}
            name="pSphere1"
            position={[0, -7.0229, 0]}
          />
          <mesh
            material={materials.blinn1}
            geometry={nodes.pPyramid1.geometry}
            name="pPyramid1"
            position={[0, -13.4908, 0]}
            rotation={[0, 0, Math.PI]}
            scale={[30, 50, 30]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/RealIsland.glb')
